import React, { useEffect, useState } from 'react';
import useProducts from './hooks/useProducts';

function App() {
  //useState restorna um estado a função para alterar o estado.

  const [ planets, setPlanets] = useState([]);
 
  /**carregaquando inicia a aplicação didMount */
  useEffect(() => {
    const  = async () => {
      
    };

   ();
  }, [])



  return (
    <div className="App">
     
    </div>
  );